### ISSUE TITLE
SW1 鐵路系統失效

### ISSUE THREAD

**Issue by davy-tw** [MinecraftSnowServer/Report#11]
SW1 (Alpha -10154, 90, -1097) 有一個單雙向鐵軌系統失效 （無法順利切換），目測是 Easycart 改變了行為

**Comment by davy-tw** [comment]
![image](https://cloud.githubusercontent.com/assets/841969/25339638/efbcd19e-2935-11e7-85fb-25069feea6eb.png)

**Comment by fntsrlike** [comment]
目前 Easycart 除了礦車不減速外，還有帶來什麼改變嗎？

**Comment by davy-tw** [comment]
礦車載的不是人的時候 行為會特別不一樣

**Comment by fntsrlike** [comment]
試用了一段時間後，能判定 Easycart 有其必要性嗎？如果不減速，動力鐵軌放多一點似乎就可以了？

行為特別不一樣是指？

**Comment by davy-tw** [comment]
主要是 EasyCart 可以突破礦車限速，還有不減速的功能，如此才能達到高鐵效果……

例如載著雞的時候會減速…… 而且會有鐘擺效果（在加速軌上坡還是會減速）

**Comment by fntsrlike** [comment]
我在 SpitgotMC 有發現可用於 1.11 版的 TrainCarts 了，可以來嘗試一下，若沒問題就可以裝回來，並取消 Easycarts。
https://www.spigotmc.org/resources/traincarts.39592/

**Comment by fntsrlike** [comment]
已實裝 TrainCarts 並且移除 EasyCarts。

**Comment by fntsrlike** [comment]
我在把 TrainCarts 和 EasyCarts 都移除的情況下進行測試。

在雪服，往車站方向行駛，都會被彈過來；
在單機（原生）則是可以正常切換。

所以推估是 Spitgot 的問題。

你怎麼看呢？ @david50407

**Comment by davy-tw** [comment]
先不考慮這個問題好了，既然不裝插件都會爆炸 那應該也沒什麼好修的了
