### ISSUE TITLE
自動重啟 Server 的 Plugin

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#16]
## AutoStart
https://www.spigotmc.org/resources/autorestart.2538/

重要的功能：
- 可以設定每幾個小時重啟一次
- 可以設定指定時間進行重啟
- 可以設定在倒數剩下多少時間時，在畫面顯示重啟倒數時間
- 再重啟前執行定指令
- 可設定若當前上線人數達多少人時，就不會重啟

@sntc06 @david50407 
你們覺得安裝這個進行固定週期重啟如何？

**Comment by fntsrlike** [comment]
自動重啟的另一個好處是，透過重啟前會存檔，可以降低伺服器崩潰造成地圖沒存檔的影響。

**Comment by sntc06** [comment]
++
如果實在是抓不到為什麼lag只能這樣了

**Comment by davy-tw** [comment]
所以他其實只是定時 shutdown server, 我們還是要自己寫 loop？ 不過可接受

**Comment by fntsrlike** [comment]
嚴重問題：啟用 `timestamp` 選項會導致多數功能失效。

**Comment by fntsrlike** [comment]
這個套件評估後問題太多，暫時移除。

**Comment by fntsrlike** [comment]
因為原本考量的套件不適用，且最近伺服器穩定，不需要再定時重開，故關閉此議題。
