### ISSUE TITLE
監控遊戲中可能和 Lag 有關的相關參數的插件：LagMonitor

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#17]
https://www.spigotmc.org/resources/lagmonitor.21348/

若一直有 Lag 問題，可以評估是否裝這個插件或類似插件來即時觀測原因。

比較有趣的是這個插件可以透過地圖實作在遊戲中觀看特定數據的示意圖。

#### 主要功能與特色：

- Save Monitoring data into a MySQL database for webinterfaces
- Player ping
- Sample CPU usage
- Analyze RAM usage
- Manage Java Flight Recordings - See this
- Access to Stacktraces of running threads
- Shows your ticks per second with history
- Shows system performance usage
- Visual graphs ingame
- Ingame timings viewer
- Access to Java environment variables (mbeans)
- Plugin specific profiles
- Thread safety checks
- Blocking operations on the main thread check
- Information about native OS
- Compatible 1.8+ servers
- Test with Spigot, PaperSpigot and TacoSpigot
- Open Source

**Comment by fntsrlike** [comment]
已由 @sntc06 實裝，正在觀察實用度。

**Comment by sntc06** [comment]
目前看起來比較像是網路問題... 系統上沒有太明顯的負載問題。

**Comment by fntsrlike** [comment]
目前已安裝並持續監控中，本 issue 算已完成，故關閉。
