### ISSUE TITLE
雪服 1.12 升級作業

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#20]
## Server

- [x] 搬遷伺服器
- [x] 升級伺服器作業系統

## Plugins 相容性測試

打勾代表有相容。

可以參考 [Spigot 1.12 Plugin Compatibility List](https://www.spigotmc.org/wiki/spigot-1-12-plugin-compatibility-list/)

### 既有 Plugin

- [x] AdminCMD
- [x] ChatEx
- [x] Dynmap-WorldGuard
- [x] ShulkerBoxPlus
- [x] LagMonitor（1.14.3）
- [x] Lift
- [x] LockettePro（2.8.1）
- [x] FastLogin
- [x] Slack
- [x] AuthMe (v5.3.1)
- [x] TreeLogging
- [x] Train_Carts
- [x] BKCommonLib
- [x] HopperHopper
- [x] Skinny
- [x] SkinnySnowServer
- [x] WorldEdit-Bukkit (v6.1.8-SNAPSHOT)
- [x] CoreProtect (v2.14.2)
- [x] Dynmap (v2.5-SNAPSHOT) 
- [x] Multiverse-Core (v2.5.0-SNAPSHOT-b727)
- [x] Multiverse-NetherPortals (v2.5-SNAPSHOT-b717)
- [x] Multiverse-Portals (v2.5-SNAPSHOT-b751)
- [x] Multiverse-SignPortals (v2.5-SNAPSHOT-b704)
- [x] PermissionsEx (v1.23.4)
- [x] ProtocolLib (v4.3.0 Build #370)
- [x] worldguard (v6.2.1) 

### 希望新增的 plugin
- [ ] AsyncWorldEdit #18  ( https://github.com/SBPrime/AsyncWorldEdit/releases/tag/2.3.3 )
- [ ] WorldGuardExtraFlags
- [ ] WorldBorder (v1.8.7)
- [ ] [PluginManager](https://www.spigotmc.org/resources/api-pluginmanager-1-8-1-9-1-10-1-11.18047/)

**Comment by davy-tw** [comment]
已升級 1.12
