### ISSUE TITLE
補完舊世界未生成的區塊

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#21]
有一個插件就做 [WorldBorder](https://mods.curse.com/bukkit-plugins/minecraft/worldborder)，他能設定世界的邊界，並在將邊界內的地圖生成完整。透過這個插件與其功能，就能將舊世界未生成的區塊重新生出來，再把它放到 Alpha 了。

> /wb [worldname] fill [freq] [pad] [force] - generate all missing chunks for this world, out to the border. The freq value is the number of times per second it will try to check/generate a chunk (default 20). For a server with players on it, you should probably stick with the default or possibly even a lower value. If you just want it to finish as quickly as possible, try 1000 or so. The pad value is how much of a buffer to add beyond your borders (default 208, should keep any more chunks from being generated by players). Specify "true" for the force value if you want to force loading of all world chunks instead of automatically skipping chunks which are already fully generated. Read below for more info.
> 
> Permission: worldborder.fill

**Comment by sntc06** [comment]
有什麼特別的用意嗎？舊世界已經不開放探勘了

**Comment by fntsrlike** [comment]
沒，純粹是看那一塊塊黑霧有點強迫症。  XDrz
我也只是先記錄下來有這種辦法可以實作，但我自己也沒時間弄這個。

因為沒有急迫性，所以先關閉此議題。
