### ISSUE TITLE
領地管理辦法

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#25]
## TODO

- [x] 對~Builder~**領主**開放 `/rg tp <region_id>` 的權限。
- [x] 修復每個人合法領地會超過三個的錯誤。
- [x] 製作領地申請辦法的~投影片~**說明文件**
- [x] 討論是否讓領地擁有者在自己領地上會自動變成創造模式。
- [x] 承上，成員是否會變成創造模式。

**Comment by davy-tw** [comment]
關於創造模式，我覺得用開放在自己領地裡面切換模式就好了
說不定也會有人想要蓋類似跑酷之類的東西，可以切換也是滿需要的

**Comment by fntsrlike** [comment]
有沒有辦法做到可以在領地自由切換模式，我還要實驗。
但目前已知是可以給他們在自己領地設置模式旗幟的權限，也是另類的切換。

**Comment by fntsrlike** [comment]
說明文件已製作完成。原訂項目皆完成，故關閉此項目。
