### ISSUE TITLE
無法登入 io.netty.handler.codec.DecoderException: Badly compressed packet

### ISSUE THREAD

**Issue by c910335** [MinecraftSnowServer/Report#28]
## 基本資訊

- 玩家 ID： `Ureezu`
- 發生時間： `2017-07-25T08:51+0800`

## 問題描述

登入時立即斷線
並出現如下圖的錯誤

`Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2181606 is larger than protocol maximum of 2097152`

![Badly compressed packet](https://cdn.discordapp.com/attachments/333255335772946453/339208478994333696/2017-07-25_8.52.11.png)

**Comment by davy-tw** [comment]
Fixed by removing broken `scordboard.dat`

**Comment by davy-tw** [comment]
for ref: https://bugs.mojang.com/browse/MC-92264
