### ISSUE TITLE
_SOZA_ 和 Eyeofthesliders 擅自拿取 danny8376 所屬界伏盒

### ISSUE THREAD

**Issue by danny8376** [MinecraftSnowServer/Report#40]
## 基本資訊

- 玩家 ID： `danny8376`
- 發生時間： `2017-08-01 22:50 左右 / 2017-08-02 14:50左右 / 2017-08-06 12:50左右`

## 問題描述

於上述數個時間點於本人家中儲物箱(`678, 124, 525`)取走數個界伏盒(有放回有取出，共計`_SOZA_`拿走 `紫色界伏盒` x1 `橘色界伏盒` x1、`Eyeofthesliders`拿走`紫色界伏盒` x1 `白色界伏盒` x1)

![image](https://user-images.githubusercontent.com/3490463/29750933-15208046-8b7b-11e7-8c46-29e364096970.png)

另尚有其他部分物資被拿走，但因較易取得暫不列入

**Comment by fntsrlike** [comment]
因本事件發生在記點條例之前，所以不朔及既往進行處分，僅作備案處理。請當事人向違規人進行歸還要求，若當事人仍無歸還意願，可再開啟本議案進行申訴。
