### ISSUE TITLE
透過 WorldGuard 的 fly 擴充旗幟開放部分飛行

### ISSUE THREAD

**Issue by fntsrlike** [MinecraftSnowServer/Report#5]
可以讓特定區域擁有飛行功能的 flag，先記著備存，可再討論有沒有這種需求。
https://mods.curse.com/bukkit-plugins/minecraft/worldguard-fly-flag

**Comment by fntsrlike** [comment]
目前想到的情況是在居住區可以設定成許可飛行，讓建造建築或機關時有一定的方便性。出了居住區，屬於冒險的範疇，就會恢復正常，不能再飛行。

**Comment by fntsrlike** [comment]
只相容到 1.8.1，且目前無急迫性。故先關閉此議題。

**Comment by fntsrlike** [comment]
https://www.spigotmc.org/resources/worldguard-extra-flags.4823/
已支援 1.12。

**Comment by fntsrlike** [comment]
測試過後，確定可以禁飛，包括在創造模式下。
效果大概是，如果處於飛行模式下，經過禁飛領域就會掉下來，無論是否屬於 OP、MOD 或是一般人。

若要達到效果的做法大概是，將 `[MOD]`、`[VIP]` 加入 `__global__` 的成員，然後將 `fly` 針對非成員的玩家設置為 `deny`，如此一般玩家就算是可以使用 `/fly` 指令也飛不起來。

**Comment by davy-tw** [comment]
掉下來感覺很痛……危險

**Comment by fntsrlike** [comment]
嗯，的確會受傷。看來要再審慎評估了。

**Comment by fntsrlike** [comment]
因為已經實裝 WorldGuard Extra Flags，所以本議題討論方向改成討論使用這插件建立部分開放飛行的必要性與可行性。

**Comment by fntsrlike** [comment]
目前無玩家再提出這份需求，且管理群對突然離開領地就會掉下去造成的損失還沒有想出配套，故先關閉此議題，有需求時再開啟。
